language: java

script: travis_wait 21 ./gradlew build

env:
  - JIRA_SOFTWARE_VERSION=8.0.0
  - JIRA_SOFTWARE_VERSION=7.13.0
  - JIRA_SOFTWARE_VERSION=7.3.0
  - JIRA_SOFTWARE_VERSION=7.2.0
stages:
  - name: release
    if: env(RELEASE) == true AND fork == false

jobs:
  include:
    - stage: release
      env: JIRA_SOFTWARE_VERSION=none
      script: ./scripts/travis-release.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
